---
title: Rtumblr - Collecting and Analyzing 'Tumblr' Data
format:
  html:
    embed-resources: true
  gfm: default
---

## Description

<!-- - Provide a brief and clear description of the method, its purpose, and what it aims to achieve. Add a link to a related paper from social science domain and show how your method can be applied to solve that research question.   -->

An implementation of calls designed to collect 'Tumblr' data via its Application Program Interfaces (API), which can be found at the following URL: <https://www.tumblr.com/docs/en/api/v2>.

## Keywords

<!-- EDITME -->

* Social Media 
* Tumblr
* Data gathering

## Science Usecase(s)

umblr's distinct culture, characterized by its use of tags, reblogging, and fandom-driven communities, provides valuable data for understanding digital identity expression, subcultures, and the viral spread of content. Researchers can analyze text, images, hashtags, and user interactions to study phenomena such as the formation of online communities, meme culture, or the role of anonymity in fostering authentic self-expression.

## Repository structure

This repository follows [the standard structure of an R package](https://cran.r-project.org/doc/FAQ/R-exts.html#Package-structure).

## Environment Setup

With R installed:

```r
install.packages("Rtumblr")
```

<!-- ## Hardware Requirements (Optional) -->
<!-- - The hardware requirements may be needed in specific cases when a method is known to require more memory/compute power.  -->
<!-- - The method need to be executed on a specific architecture (GPUs, Hadoop cluster etc.) -->


## Input Data 

<!-- - The input data has to be a Digital Behavioral Data (DBD) Dataset -->
<!-- - You can provide link to a public DBD dataset. GESIS DBD datasets (https://www.gesis.org/en/institute/digital-behavioral-data) -->

<!-- This is an example -->

The package is used to gather data from Tumblr


## How to Use

Most API endpoints only work with your own account. The ones already
implemented include:

- `get_blog_blocks()`: get a list of accounts you blocked
- `get_blog_likes()`: get a list of posts you liked
- `get_blog_followers()`: get your followers
- `get_blog_following()`: get accounts you follow

Implemented endpoints that work with any account are:

- `get_blog_avatar()`: get the avatar of a blog
- `get_blog_info()`: get the general info of a blog
- `get_blog_posts()`: get the posts of a blog
- `get_posts_tag()`: get posts with a specific tag.

All function return a tibble (or list of tibble). To get information
about columns, see the official API documentation:
<https://www.tumblr.com/docs/en/api/v2>


## Contact Details

Maintainer: David Schoch <david@schochastics.net>

Issue Tracker: [https://github.com/schochastics/Rtumblr/issues](https://github.com/schochastics/Rtumblr/issues)

<!-- ## Publication -->
<!-- - Include information on publications or articles related to the method, if applicable. -->

<!-- ## Acknowledgements -->
<!-- - Acknowledgements if any -->

<!-- ## Disclaimer -->
<!-- - Add any disclaimers, legal notices, or usage restrictions for the method, if necessary. -->
